### ISSUE TITLE
Development moved?

### ISSUE THREAD

**Issue by georgefst** [circuithub/nix-buildkite#12]
What's the relationship between this and https://github.com/circuithub/nix-buildkite-buildkite-plugin? Should this repository be archived to prevent confusion?

**Comment by ocharles** [comment]
Yes, it should be archived. I'll do that now. https://github.com/circuithub/nix-buildkite-buildkite-plugin is the correct repo, because of the way Buildkite plugins are named (`foo/bar` resolves to the repository `foo/bar-buildkite-plugin`)
